[project]
name = "junior"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "flask>=3.1.1",
    "flask-cors>=5.0.0",
    "requests>=2.32.4",
    "claude_code_sdk",
    "GitPython>=3.1.0",
]
